name: worker-manager-nestjs-redis

services:
  redis:
    image: redis:7-alpine
    ports:
      - '6410:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s
      retries: 15
